<template>
  <div class="invoice-list" :key="componentKey">
    <!-- Decorative background elements -->
    <div class="bg-decoration-container">
      <div class="bg-circle circle-1"></div>
      <div class="bg-circle circle-2"></div>
      <div class="bg-circle circle-3"></div>
      <div class="bg-circle circle-4"></div>
      <div class="bg-blob blob-1"></div>
      <div class="bg-blob blob-2"></div>
    </div>
    
    <!-- Header section with title and search/create controls - now with enhanced background -->
    <div class="d-flex flex-column flex-sm-row align-sm-center justify-space-between py-4 px-4 px-sm-6 header-section">
      <h2 class="text-h5 text-sm-h4 mb-4 mb-sm-0 text-white">Invoice List</h2>
      <div class="d-flex flex-column flex-sm-row w-100 w-sm-auto">
        <v-text-field
          v-model="search"
          prepend-inner-icon="mdi-magnify"
          label="Search"
          hide-details
          variant="solo"
          density="compact"
          class="mb-3 mb-sm-0 mr-0 mr-sm-4 search-field"
          style="max-width: 100%;"
          bg-color="white"
        ></v-text-field>
        <v-btn color="accent" @click="navigateToCreateInvoice" class="mt-0 create-btn" elevation="3">
          <span class="d-none d-sm-block">Create Invoice</span>
          <span class="d-sm-none">Create</span>
        </v-btn>
      </div>
    </div>

    <!-- Filter section with softer background and new design -->
    <div class="d-flex px-4 px-sm-6 py-2 py-sm-4 filter-section">
      <v-menu>
        <template v-slot:activator="{ props }">
          <v-btn
            color="white"
            variant="outlined"
            v-bind="props"
            class="text-capitalize text-body-2 text-sm-body-1 filter-btn"
            size="small"
          >
            <span class="d-none d-sm-block black--text">Generated by Filter</span>
            <span class="d-sm-none black--text">Filter</span>
            <v-icon color="black">mdi-chevron-down</v-icon>
          </v-btn>
        </template>
        <v-list>
          <v-list-item value="all" @click="filter = 'all'">
            <v-list-item-title>All</v-list-item-title>
          </v-list-item>
          <v-list-item value="user" @click="filter = 'user'">
            <v-list-item-title>User Generated</v-list-item-title>
          </v-list-item>
          <v-list-item value="panel" @click="filter = 'panel'">
            <v-list-item-title>Panel Generated</v-list-item-title>
          </v-list-item>
        </v-list>
      </v-menu>
    </div>
    
    <!-- Stats Cards - Desktop View - Now with glass effect -->
    <div class="d-none d-sm-flex px-6 mb-4">
      <!-- Total Card -->
      <v-card width="33%" class="mr-2 rounded-lg stat-card total-card glass-card">
        <v-card-text class="pa-4 white--text">
          <div class="text-h4 font-weight-bold">{{ invoices.length }}</div>
          <div class="text-subtitle-1">Total</div>
        </v-card-text>
      </v-card>
      
      <!-- User Generated Card -->
      <v-card width="33%" class="mx-2 rounded-lg stat-card user-card glass-card">
        <v-card-text class="pa-4 white--text">
          <div class="text-h4 font-weight-bold">{{ userGeneratedCount }}</div>
          <div class="text-subtitle-1">User Generated</div>
        </v-card-text>
      </v-card>
      
      <!-- Panel Generated Card -->
      <v-card width="33%" class="ml-2 rounded-lg stat-card panel-card glass-card">
        <v-card-text class="pa-4 white--text">
          <div class="text-h4 font-weight-bold">{{ panelGeneratedCount }}</div>
          <div class="text-subtitle-1">Panel Generated</div>
        </v-card-text>
      </v-card>
    </div>

    <!-- Stats Cards - Mobile View - Now with glass effect -->
    <div class="d-flex d-sm-none flex-wrap px-4 mb-4">
      <!-- Total Card -->
      <v-card width="100%" class="mb-2 rounded-lg stat-card-mobile total-card-mobile glass-card">
        <v-card-text class="pa-3 white--text d-flex justify-space-between align-center">
          <div class="text-subtitle-1">Total</div>
          <div class="text-h5 font-weight-bold">{{ invoices.length }}</div>
        </v-card-text>
      </v-card>
      
      <!-- User Generated Card -->
      <v-card width="calc(50% - 4px)" class="mr-1 mb-2 rounded-lg stat-card-mobile user-card-mobile glass-card">
        <v-card-text class="pa-3 d-flex flex-column align-center white--text">
          <div class="text-h6 font-weight-bold">{{ userGeneratedCount }}</div>
          <div class="text-caption">User</div>
        </v-card-text>
      </v-card>
      
      <!-- Panel Generated Card -->
      <v-card width="calc(50% - 4px)" class="ml-1 mb-2 rounded-lg stat-card-mobile panel-card-mobile glass-card">
        <v-card-text class="pa-3 d-flex flex-column align-center white--text">
          <div class="text-h6 font-weight-bold">{{ panelGeneratedCount }}</div>
          <div class="text-caption">Panel</div>
        </v-card-text>
      </v-card>
    </div>
    
    <!-- Main content wrapper with glass effect -->
    <div class="content-wrapper">
      <!-- Invoice Table - Desktop View with alternating row colors -->
      <div class="d-none d-md-block">
        <v-table class="mx-6 invoice-table">
          <thead>
            <tr class="table-header">
              <th>ID</th>
              <th>Initiated On</th>
              <th>Generated By</th>
              <th>Customer Name</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="(invoice, index) in paginatedInvoices" :key="invoice.id" 
                class="invoice-row" 
                :class="index % 2 === 0 ? 'even-row' : 'odd-row'">
              <td>{{ invoice.id }}</td>
              <td>{{ invoice.initiatedOn }}</td>
              <td>
                <v-chip 
                  size="small" 
                  :color="invoice.generatedBy === 'User' ? 'user-chip' : 'panel-chip'"
                  text-color="white"
                  label
                >
                  {{ invoice.generatedBy }}
                </v-chip>
              </td>
              <td>
                {{ invoice.customerName }}
                <div class="text-caption">{{ invoice.customerMobile }}</div>
              </td>
              <td>
                <v-btn
                  variant="elevated"
                  color="secondary"
                  size="small"
                  @click="editInvoice(invoice.id)"
                  class="edit-btn"
                >
                  Edit
                </v-btn>
              </td>
            </tr>
          </tbody>
        </v-table>
      </div>
      
      <!-- Invoice List - Mobile/Tablet View with colorful cards -->
      <div class="d-block d-md-none px-4">
        <v-card
          v-for="invoice in paginatedInvoices" 
          :key="invoice.id"
          class="mb-3 invoice-card-mobile glass-card-light" 
          variant="outlined"
          :class="invoice.generatedBy === 'User' ? 'user-border' : 'panel-border'"
        >
          <v-card-text class="pa-3">
            <div class="d-flex justify-space-between align-center mb-2">
              <div class="text-subtitle-2 font-weight-bold">
                ID: {{ invoice.id }}
              </div>
              <v-chip 
                size="small" 
                :color="invoice.generatedBy === 'User' ? 'user-chip' : 'panel-chip'"
                text-color="white"
                label
                class="text-caption"
              >
                {{ invoice.generatedBy }}
              </v-chip>
            </div>
            
            <div class="d-flex align-start mb-1">
              <v-icon size="small" class="mt-1 mr-2" :color="invoice.generatedBy === 'User' ? '#7E57C2' : '#26A69A'">mdi-account</v-icon>
              <div>
                <div class="text-body-2 font-weight-medium">{{ invoice.customerName }}</div>
                <div class="text-caption">{{ invoice.customerMobile }}</div>
              </div>
            </div>
            
            <div class="d-flex align-center mb-3">
              <v-icon size="small" class="mr-2" :color="invoice.generatedBy === 'User' ? '#7E57C2' : '#26A69A'">mdi-calendar</v-icon>
              <div class="text-caption">{{ invoice.initiatedOn }}</div>
            </div>
            
            <div class="d-flex justify-end">
              <v-btn
                variant="elevated"
                :color="invoice.generatedBy === 'User' ? 'user-chip' : 'panel-chip'"
                size="small"
                density="comfortable"
                @click="editInvoice(invoice.id)"
                class="edit-btn white--text"
              >
                Edit Invoice
              </v-btn>
            </div>
          </v-card-text>
        </v-card>
        
        <!-- Empty state for mobile view -->
        <v-card v-if="filteredInvoices.length === 0" class="pa-4 text-center empty-state-card glass-card-light">
          <v-icon size="large" color="grey-lighten-1" class="mb-2">mdi-file-document-outline</v-icon>
          <div class="text-body-1 mb-1">No invoices found</div>
          <div class="text-caption text-grey">Try adjusting your search or filter</div>
        </v-card>
      </div>
      
      <!-- Pagination component with custom colors -->
      <div class="d-flex justify-center pa-4" v-if="filteredInvoices.length > 0">
        <v-pagination
          v-model="page"
          :length="Math.ceil(filteredInvoices.length / itemsPerPage)"
          :total-visible="isMobile ? 3 : 7"
          rounded
          class="mt-2 custom-pagination"
          active-color="secondary"
        ></v-pagination>
      </div>
    </div>
    
    <!-- Floating action button for mobile -->
    <v-btn
      class="d-block d-sm-none"
      color="accent"
      icon
      size="large"
      style="position: fixed; bottom: 16px; right: 16px; z-index: 5;"
      @click="navigateToCreateInvoice"
      elevation="5"
    >
      <v-icon>mdi-plus</v-icon>
    </v-btn>
  </div>
</template>

<script>
export default {
  name: 'InvoiceList',
  data() {
    return {
      search: '',
      filter: 'all',
      componentKey: 0,
      windowWidth: window.innerWidth,
      page: 1,
      itemsPerPage: 10
    }
  },
  computed: {
    invoices() {
      return this.$store.getters.getInvoices || [];
    },
    userGeneratedCount() {
      return this.$store.getters.getUserGeneratedCount || 0;
    },
    panelGeneratedCount() {
      return this.$store.getters.getPanelGeneratedCount || 0;
    },
    filteredInvoices() {
      return this.invoices.filter(invoice => {
        const matchesSearch = 
          (invoice.customerName ? invoice.customerName.toLowerCase().includes(this.search.toLowerCase()) : false) ||
          (invoice.customerMobile ? invoice.customerMobile.includes(this.search) : false) ||
          (invoice.id ? invoice.id.toString().includes(this.search) : false);
        
        if (this.filter === 'all') return matchesSearch;
        if (this.filter === 'user') return matchesSearch && invoice.generatedBy === 'User';
        if (this.filter === 'panel') return matchesSearch && invoice.generatedBy === 'Panel';
        
        return matchesSearch;
      });
    },
    paginatedInvoices() {
      const start = (this.page - 1) * this.itemsPerPage;
      const end = start + this.itemsPerPage;
      return this.filteredInvoices.slice(start, end);
    },
    isMobile() {
      return this.windowWidth < 600;
    }
  },
  created() {
    window.addEventListener('resize', this.handleResize);
    // Add route change event listener
    this.$router.afterEach(() => {
      this.fetchInvoices();
    });
    
    // Initial fetch
    this.fetchInvoices();
  },
  unmounted() {
    window.removeEventListener('resize', this.handleResize);
  },
  mounted() {
    this.handleResize();
    this.animateBackground();
  },
  // Updated navigation guards
  beforeRouteEnter(to, from, next) {
    next(vm => {
      // Force refresh when entering this route
      vm.refreshComponent();
    });
  },
  beforeRouteUpdate(to, from, next) {
    next();
    this.refreshComponent();
  },
  methods: {
    handleResize() {
      this.windowWidth = window.innerWidth;
      
      // Adjust items per page based on screen size
      if (this.windowWidth < 600) {
        this.itemsPerPage = 5;
      } else if (this.windowWidth < 960) {
        this.itemsPerPage = 8;
      } else {
        this.itemsPerPage = 10;
      }
    },
    async fetchInvoices() {
      console.log('Fetching invoices...');
      try {
        await this.$store.dispatch('fetchInvoices');
        console.log('Invoices fetched successfully');
      } catch (error) {
        console.error('Error fetching invoices:', error);
      }
    },
    refreshComponent() {
      this.componentKey += 1;
      this.fetchInvoices();
    },
    navigateToCreateInvoice() {
      this.$store.commit('RESET_CURRENT_INVOICE');
      this.$router.push('/invoice/create');
    },
    editInvoice(id) {
      const invoice = this.invoices.find(inv => inv.id === id);
      if (invoice) {
        this.$store.commit('SET_CURRENT_INVOICE', invoice);
        this.$router.push('/invoice/create');
      }
    },
    animateBackground() {
      // This is just a placeholder - in a real app, you might use a library 
      // like GSAP for more advanced animations
      console.log('Background animations initialized');
    }
  },
  watch: {
    search() {
      // Reset to first page when search changes
      this.page = 1;
    },
    filter() {
      // Reset to first page when filter changes
      this.page = 1;
    },
    // Watch $route to detect navigation back to this component
    $route(to) {
      if (to.path.includes('/invoice/list')) {
        this.refreshComponent();
      }
    }
  }
}
</script>

<style scoped>
/* Colorful styles for the invoice list */

/* Background styling and decorations */
.invoice-list {
  position: relative;
  min-height: 100vh;
  background: linear-gradient(135deg, #f5f7fa 0%, #e4e8f7 100%);
  overflow: hidden;
}

.bg-decoration-container {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  z-index: 0;
  overflow: hidden;
}

.bg-circle {
  position: absolute;
  border-radius: 50%;
  opacity: 0.4;
}

.circle-1 {
  width: 300px;
  height: 300px;
  top: -100px;
  right: -50px;
  background: linear-gradient(45deg, #050505, #201e1c);
  animation: float 15s ease-in-out infinite;
}

.circle-2 {
  width: 200px;
  height: 200px;
  bottom: 10%;
  left: -50px;
  background: linear-gradient(45deg, #7F7FD5, #91EAE4);
  animation: float 20s ease-in-out infinite reverse;
}

.circle-3 {
  width: 150px;
  height: 150px;
  top: 20%;
  left: 10%;
  background: linear-gradient(45deg, #BE93C5, #7BC6CC);
  animation: pulse 12s ease-in-out infinite;
}

.circle-4 {
  width: 180px;
  height: 180px;
  bottom: 15%;
  right: 5%;
  background: linear-gradient(45deg, #070707, #3a3a3a);
  animation: float 18s ease-in-out 2s infinite;
}

.bg-blob {
  position: absolute;
  border-radius: 30% 70% 70% 30% / 30% 30% 70% 70%;
  opacity: 0.5;
}

.blob-1 {
  width: 400px;
  height: 400px;
  top: 30%;
  right: -100px;
  background: linear-gradient(45deg, #42275a, #734b6d);
  animation: morphBlob 20s ease-in-out infinite alternate;
}

.blob-2 {
  width: 350px;
  height: 350px;
  bottom: -100px;
  left: 20%;
  background: linear-gradient(45deg, #1D976C, #93F9B9);
  animation: morphBlob 25s ease-in-out 2s infinite alternate-reverse;
}

@keyframes float {
  0% { transform: translateY(0) rotate(0deg); }
  50% { transform: translateY(-20px) rotate(5deg); }
  100% { transform: translateY(0) rotate(0deg); }
}

@keyframes pulse {
  0% { transform: scale(1); opacity: 0.4; }
  50% { transform: scale(1.1); opacity: 0.6; }
  100% { transform: scale(1); opacity: 0.4; }
}

@keyframes morphBlob {
  0% { border-radius: 30% 70% 70% 30% / 30% 30% 70% 70%; }
  25% { border-radius: 58% 42% 75% 25% / 76% 46% 54% 24%; }
  50% { border-radius: 50% 50% 33% 67% / 55% 27% 73% 45%; }
  75% { border-radius: 33% 67% 58% 42% / 63% 68% 32% 37%; }
  100% { border-radius: 30% 70% 70% 30% / 30% 30% 70% 70%; }
}

/* Content wrapper with glass effect */
.content-wrapper {
  position: relative;
  z-index: 1;
  background: rgba(255, 255, 255, 0.2);
  backdrop-filter: blur(10px);
  -webkit-backdrop-filter: blur(10px);
  margin: 0 16px;
  border-radius: 16px;
  box-shadow: 0 8px 32px rgba(31, 38, 135, 0.1);
  border: 1px solid rgba(255, 255, 255, 0.18);
}

/* Glass effect cards */
.glass-card {
  backdrop-filter: blur(16px) !important;
  -webkit-backdrop-filter: blur(16px) !important;
  border: 1px solid rgba(255, 255, 255, 0.3) !important;
  box-shadow: 0 8px 32px rgba(31, 38, 135, 0.2) !important;
}

.glass-card-light {
  background: rgba(255, 255, 255, 0.6) !important;
  backdrop-filter: blur(10px) !important;
  -webkit-backdrop-filter: blur(10px) !important;
  border: 1px solid rgba(255, 255, 255, 0.3) !important;
  box-shadow: 0 4px 16px rgba(31, 38, 135, 0.1) !important;
}

/* Header section with gradient background */
.header-section {
  background: linear-gradient(135deg, #2cb69b, #28bd9f);
  border-radius: 16px;
  box-shadow: 0 4px 8px rgba(0,0,0,0.1);
  position: relative;
  z-index: 2;
  margin: 16px 16px 0 16px;
}

/* Filter section background */
.filter-section {
  background-color: rgba(255, 255, 255, 0.3);
  backdrop-filter: blur(5px);
  -webkit-backdrop-filter: blur(5px);
  border-bottom: 1px solid rgba(255, 255, 255, 0.2);
  position: relative;
  z-index: 1;
  margin: 0 16px;
}

/* Search field styling */
.search-field {
  border-radius: 20px;
  overflow: hidden;
}

/* Create button styling */
.create-btn {
  background: linear-gradient(45deg, #67d6c0, #71dcc7) !important;
  border-radius: 20px;
  transition: transform 0.2s, box-shadow 0.2s;
}

.create-btn:hover {
  transform: translateY(-2px);
  box-shadow: 0 4px 8px rgba(15, 15, 15, 0.4) !important;
}

/* Stats cards styling */
.total-card {
  background: linear-gradient(135deg, #2cb69b, #2cb69b);
}

.user-card {
  background: linear-gradient(135deg, #2cb69b, #2cb69b);
}

.panel-card {
  background: linear-gradient(135deg, #2cb69b, #2cb69b);
}

/* Mobile stats cards */
.total-card-mobile {
  background: linear-gradient(to right, #5fc4b0, #6cd6bb);
}

.user-card-mobile {
  background: linear-gradient(to right, #099075, #6cd0d6);
}

.panel-card-mobile {
  background: linear-gradient(to right, #099075, #6cd0d6);
}

/* Table styling */
.invoice-table {
  border-radius: 8px;
  overflow: hidden;
  box-shadow: 0 2px 4px rgba(0,0,0,0.05);
  background: rgba(255, 255, 255, 0.9);
}

.table-header {
  background: linear-gradient(to right, #22b89a, #2ac7a8);
  color: white;
}

.table-header th {
  font-weight: 600;
  padding: 12px 16px;
}

.even-row {
  background-color: rgba(249, 249, 249, 0.8);
}

.odd-row {
  background-color: rgba(255, 255, 255, 0.8);
}

/* Invoice row hover effect */
.invoice-row {
  transition: background-color 0.2s, transform 0.2s;
}

.invoice-row:hover {
  background-color: rgba(237, 231, 246, 0.8);
  transform: scale(1.01);
}

/* Custom chip colors */
:deep(.user-chip) {
  background: linear-gradient(45deg, #67e99b, #20935b) !important;
}

:deep(.panel-chip) {
  background: linear-gradient(45deg, #67e99b, #20935b) !important;
}

/* Mobile card styling */
.invoice-card-mobile {
  border-radius: 12px;
  transition: transform 0.2s, box-shadow 0.2s;
}

.user-border {
  border-left: 4px solid #00B4DB !important;
}

.panel-border {
  border-left: 4px solid #FF416C !important;
}

.invoice-card-mobile:hover {
  transform: translateY(-3px);
  box-shadow: 0 5px 15px rgba(0,0,0,0.1) !important;
}

/* Edit button hover effects */
.edit-btn {
  transition: transform 0.2s, box-shadow 0.2s;
  border-radius: 20px;
}

.edit-btn:hover {
  transform: translateY(-2px);
  box-shadow: 0 3px 6px rgba(0,0,0,0.15) !important;
}

/* Empty state card */
.empty-state-card {
  background-color: rgba(250, 250, 250, 0.6);
  border-radius: 12px;
}

/* Custom pagination */
:deep(.custom-pagination .v-pagination__item--active) {
  background: linear-gradient(45deg, #67e99b, #20935b) !important;
}

/* Card hover animations */
.stat-card, .stat-card-mobile {
  transition: transform 0.3s, box-shadow 0.3s;
}

.stat-card:hover, .stat-card-mobile:hover {
  transform: translateY(-4px);
  box-shadow: 0 8px 16px rgba(0,0,0,0.15) !important;
}

@media (max-width: 600px) {
  /* Mobile-specific styles */
  :deep(.v-field__input) {
    font-size: 14px !important;
    padding: 8px !important;
  }
  
  /* Rounded corners for mobile */
  .invoice-card-mobile {
    border-radius: 10px;
  }
  
  /* Scale down background elements on mobile */
  .bg-circle, .bg-blob {
    transform: scale(0.7);
  }
}

/* Filter button styling */
.filter-btn {
  border-color: rgba(255, 255, 255, 0.5) !important;
  color: #185a9d !important;
  backdrop-filter: blur(5px);
  -webkit-backdrop-filter: blur(5px);
  transition: background-color 0.2s, transform 0.2s;
}

.filter-btn:hover {
  background-color: rgba(255, 255, 255, 0.3) !important;
  transform: translateY(-1px);
}

.filter-btn :deep(.v-btn__content) {
  color: #185a9d !important;
}
</style>